# Generated by Django 5.0.4 on 2024-10-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolyear',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
